### ISSUE TITLE
pyVHR==0.3 is required

### ISSUE THREAD

**Issue by Arritmic** [phuselab/pyVHR#1]
Hello,

I have installed _pyvhr_ as explained in the README file, but I am having the next error:
```
Installed /home/arritmic/anaconda3/envs/myenv/lib/python3.8/site-packages/pyVHR-0.0.1-py3.8.egg
Processing dependencies for pyVHR==0.0.1
error: pyVHR 0.0.1 is installed but pyVHR==0.3 is required by {'pyVHR'}
```
![Screenshot from 2020-11-23 15-19-18](https://user-images.githubusercontent.com/9532966/99967342-62c49600-2da0-11eb-8944-34cc4a3d1476.png)

![Screenshot from 2020-11-23 15-19-04](https://user-images.githubusercontent.com/9532966/99967358-6d7f2b00-2da0-11eb-84a2-9e69b2d5e0af.png)

I was wondering if you should change the version of _pyVHR_ in requirements file or it is something I am not taking into account...

Thanks.
A

**Comment by vcuculo** [comment]
Thank you @Arritmic , commit  5f6752d951dd28206f790df5417aa94465139ca3 fix this. Please follow the README and let us know if this solves the problem.
