### ISSUE TITLE
Cannot clone repository due to invalid path 'results/ALL_WIN10/Cohface_03-13-2020_15:11_winSize10'

### ISSUE THREAD

**Issue by LegrandNico** [phuselab/pyVHR#12]
Hi,

thank you for your work on this project, the package looks super helpful. I would like to see how easily the analysis pipeline could be interfaced with Psychopy to perform remote PPG during psychological experiments.

However, for now, I am not able to clone the repository due to the path error I am reporting in the title.

**Comment by vcuculo** [comment]
@LegrandNico thank you very much for your feedback!
Could you please explain how are you cloning the repository?
I see no issues with the following command
`git clone git@github.com:phuselab/pyVHR.git`

Thank you!

**Comment by LegrandNico** [comment]
I am using the git clone command from VS code, and get the following output:

```
error: invalid path 'results/ALL_WIN10/Cohface_03-13-2020_15:11_winSize10'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

Also, I should say that I am using Windows 10.

From what I see it is likely that the `:` in the file name is causing the error.

**Comment by vcuculo** [comment]
Oh yes, following the Windows' [naming convention](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) is looks like colon is not an allowed character. We will fix this as soon as possible. Thank you!

**Comment by aledamelio** [comment]
@LegrandNico commit 758364e92dab384fe49be975eba380d157da21a7 should fix this. Let us know if everything works fine now.

**Comment by LegrandNico** [comment]
Yes, this is working perfectly now, thank you.
