### ISSUE TITLE
Subset Mahnob

### ISSUE THREAD

**Issue by Arritmic** [phuselab/pyVHR#22]
Hi,
In your manuscript, you say:

> In this paper only a subset of the video data has been used.

Could you specify which is that subset? Which videos are included? I could not find in the framework or original paper which videos are used to evaluate.

Thanks in advance.

**Comment by aledamelio** [comment]
Hello @Arritmic,

yes, some of the Mahnob videos had issues concerning the time correspondence between video and physiological signals. For this reason we selected the subset of videos for which the difference in length (seconds) between video and physiological traces was less that 1 second. 

This is the list of the videos used in the analysis:

10    1198  1576  2094  2226  2604  2634  2888  3388  3644  556  808  1042  1322  1590  2114  2246  2606  274   3006  3396  3662  800  814  1184  152   1698  2120  2346  2624  276   3136  34    408   806  926

Hope this helps,

Alessandro

**Comment by Arritmic** [comment]
Yes, it helps. Thanks so much for the effort Alessandro.

Best wishes,
Tino
