### ISSUE TITLE
Basic demo Files (Ground truth values )

### ISSUE THREAD

**Issue by saranzeb** [phuselab/pyVHR#29]
hello sir   need a little help regarding 
Do we need the ground truth values for notebook (basic demo and factory demo  ) files if yes from where we can get it i.e. from where we can get the BVP files for BVPdateDIR ?  and what about the other datasets like LGI_PPGI etc  do they have the ground truth files ie its bvp and ecg files or we have to create by ourselves  
Another question the IDI files containing some Videos' s what about other (xml) files they have like 
cms50_stream_handler
andc
v_camera_sensor_timer_stream_handler 
they are having the BVP or BPM and time values ?

**Comment by vcuculo** [comment]
Thank you @saranzeb for your issue. First of all, please be sure that you are using the last version of pyVHR.

Every dataset does already include the ground-truth files, and you don't have to create them by yourself.
For each supported dataset we provide an interface to read both the videos and the related ground-truth files (the XML ones). In case of `LGI-PPGI` [here](https://github.com/phuselab/pyVHR/blob/master/pyVHR/datasets/lgi_ppgi.py) is where the ground-truth is extracted.

The `BVPdataDIR` used in the `pyVHR_demo` [notebook](https://github.com/phuselab/pyVHR/blob/master/notebooks/pyVHR_demo.ipynb) , in case of `LGI-PPGI` should be set to the root of the dataset.

Hope it helps.

**Comment by saranzeb** [comment]
> Thank you @saranzeb for your issue. First of all, please be sure that you are using the last version of pyVHR.
> 
> Every dataset does already include the ground-truth files, and you don't have to create them by yourself. For each supported dataset we provide an interface to read both the videos and the related ground-truth files (the XML ones). In case of `LGI-PPGI` [here](https://github.com/phuselab/pyVHR/blob/master/pyVHR/datasets/lgi_ppgi.py) is where the ground-truth is extracted.
> 
> The `BVPdataDIR` used in the `pyVHR_demo` [notebook](https://github.com/phuselab/pyVHR/blob/master/notebooks/pyVHR_demo.ipynb) , in case of `LGI-PPGI` should be set to the root of the dataset.
> 
> Hope it helps.

Thank you very much yes it helped a lot thanks  
sorry one last question should we run the the interface first to read the bvp files and then put  those values in directory of  BVPDataDIR or we just give the path to the File containing both video's and BVP files and it will automatically read the ground truth values from XML files for pyVHR_demo

**Comment by vcuculo** [comment]
The second one, exactly as done in the `pyVHR_demo` notebook.
This row, in the `Initial setup` section does import the entire dataset
```python
dataset = vhr.datasets.datasetFactory(dataset_name, videodataDIR=video_DIR, BVPdataDIR=BVP_DIR)
```

**Comment by saranzeb** [comment]
ok thanks again for your precious time as for me i have just ID1  of LGI-PPGI  which has 4 files  alex -gym,alex-resting,alex-rotation,alex-talk
1) cms50_stream_handler
2) cv_camera_sensor_stream_handler
3) cv_camera_sensor_timer_stream_handler
So i have to gave the path of any of the four files for both video-DIR and BVP_DIR  ?

**Comment by giulianogrossi** [comment]
A new version of the framework, pyVHR 2.0, has been released. Please check if problems persist and report them for future bug fixes.

best
the pyVHR team
