### ISSUE TITLE
ResolvePackageNotFound: Error

### ISSUE THREAD

**Issue by wgb-10** [phuselab/pyVHR#32]
When trying to create the conda environments using the installation instructions given in the readme, I get the ResolvePackageNotFound error as shown in the image below:

![pyVHR_Issue1](https://user-images.githubusercontent.com/55624355/147885033-b7bd4c82-a0e0-40d5-9bc2-5132ab6d247b.jpg)

The same error appears when trying to create the environment for the CPU only version as shown below:

![pyVHR_Issue2](https://user-images.githubusercontent.com/55624355/147885066-6e7e59ff-a646-4385-ae38-423dd3a57bf1.jpg)

I eventually was able to install the framework by creating my own environment manually and installing the required packages which was quite tedious.

**Comment by nellorebhanuteja** [comment]
i am facing the same issue
any resolution ?

**Comment by wgb-10** [comment]
@nellorebhanuteja I installed the libraries under the 'Custom Installation' section into my conda environment and then ran:

```bash
git clone git@github.com:phuselab/pyVHR.git
cd pyVHR/
python setup.py install
```
Whenever there was an error (due to package dependencies) I manually installed those and ran 'python setup.py install' again.

**Comment by wgb-10** [comment]
Commit c6ea98b9e2336ef1b751f0af44d6fb5aa44d7704 resolves this issue.
