### ISSUE TITLE
Subjects in UBFC2

### ISSUE THREAD

**Issue by Arritmic** [phuselab/pyVHR#33]
Hi,

Could you tell me what subjects you have used to evaluate the UBFC2? The dataset contains 42 subjects but in the results appear 24.

Thanks in advance.

**Comment by giulianogrossi** [comment]
Hi,
we are planning to test all the videos in UBFC2, but for the moment we have only included the subjects: 1, 3, 10, 11, 12, 13, 14, 15, 16, 17, 18, 20, 22, 23, 24, 25, 26, 27, 30,  31, 32, 33, 34, 35, 36, 37.

best

**Comment by Arritmic** [comment]
Thanks Giuliano!!!!
