### ISSUE TITLE
Issue while creating the pyvhr environment

### ISSUE THREAD

**Issue by Lokesh-Vakkalakula** [phuselab/pyVHR#35]
Unfortunately I am facing issue in windows 10 while creating pyvhr environment. Have tried in anaconda and then downloaded minianaconda also, but got same issue. Any leads would be helpful. Please check.

conda env create --file https://raw.githubusercontent.com/phuselab/pyVHR/pyVHR_CPU/pyVHR_CPU_env.yml

######error#######
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:

ncurses=6.2
libidn2=2.3.2
nettle=3.7.3
_openmp_mutex=4.5
libgcc-ng=11.2.0
libstdcxx-ng=11.2.0
libunistring=0.9.10
lame=3.100
openh264=2.1.0
ld_impl_linux-64=2.35.1
nss=3.69
libgomp=11.2.0
gmp=6.2.1
libtasn1=4.16.0
gnutls=3.6.15
nspr=4.30
libuuid=2.32.1
readline=8.1

**Comment by MichaelMakelko** [comment]
got the same Issue

**Comment by wgb-10** [comment]
Commit c6ea98b9e2336ef1b751f0af44d6fb5aa44d7704 resolves this issue.
