### ISSUE TITLE
list index out of range in while executing rPPG method(part)

### ISSUE THREAD

**Issue by rupakkatwal** [phuselab/pyVHR#4]
**cfgFilename = '/Users/rupakkatwal/Downloads/pyVHR-master/pyVHR/analysis/sample.cfg'
test = TestSuite(configFilename=cfgFilename)
result = test.start(outFilename='sampleExp.h5', verb=4)**

IndexError                                Traceback (most recent call last)
<ipython-input-58-01da782e5e24> in <module>
      1 cfgFilename = '/Users/rupakkatwal/Downloads/pyVHR-master/pyVHR/analysis/sample.cfg'
      2 test = TestSuite(configFilename=cfgFilename)
----> 3 result = test.start(outFilename='sampleExp.h5', verb=4)

~/opt/anaconda3/lib/python3.8/site-packages/pyVHR/analysis/testsuite.py in start(self, saveResults, outFilename, verb)
     58 
     59                 # -- video object
---> 60                 videoFilename = dataset.getVideoFilename(v)
     61                 video = Video(videoFilename, verb)
     62                 video.getCroppedFaces(detector=self.videodict['detector'],

~/opt/anaconda3/lib/python3.8/site-packages/pyVHR/datasets/dataset.py in getVideoFilename(self, videoIdx)
     49     def getVideoFilename(self, videoIdx=0):
     50         """Get video filename given the progressive index"""
---> 51         return self.videoFilenames[videoIdx]
     52 
     53     def getSigFilename(self, videoIdx=0):

IndexError: list index out of range

**Comment by aledamelio** [comment]
Thank you @floki567, commit d8658b010b26ec3ff205d0f832368f39783a4d06 fixes this. Please follow carefully the instructions in the basic_demo notebook and let us know if this solves the problem.

**Comment by floki567** [comment]
The error is still the same.  I reinstall the pyvhr and use the updated sample.cfg and follow the exact basic step , but the error is the same.

**Comment by vcuculo** [comment]
@floki567 are you using the pip version or the source code? we did not release a new version of the package yet. Until then, you should adopt the version from master branch. Thanks!

**Comment by rupakkatwal** [comment]
i use master brach to install pyvhr 0.0.2, followed the demo but the error is same

**Comment by talhaanwarch** [comment]
I am getting this error. though I have installed it from the master source. What is the solution
