### ISSUE TITLE
Error Found When Plotting Window 

### ISSUE THREAD

**Issue by wgb-10** [phuselab/pyVHR#40]
In `pyVHR_demo.ipynb` the current code uses a hardcoded value of 18, which can be more than the total number of windows. 

![image](https://user-images.githubusercontent.com/55624355/162762371-6b0c1d6a-eb82-498a-9fb1-3fb66ec59e85.png)

It should instead use the value of w (window number) generated:

![image](https://user-images.githubusercontent.com/55624355/162762656-57a356df-9e6e-4c8c-86bc-f7f7bdd842e6.png)

**Comment by aledamelio** [comment]
Hi @wgb-10,
thanks for raising this issue... You're right! commit 580eff708eb4965d9daa86b64558379a86eb41ab should solve this.
Cheers,
Alessandro
