### ISSUE TITLE
winSizeGT is not defined in pyVHR_demo_deep.ipynb

### ISSUE THREAD

**Issue by wgb-10** [phuselab/pyVHR#41]
The issue is in this cell of pyVHR_demo_deep.ipynb:

![image](https://user-images.githubusercontent.com/55624355/163141731-15d66138-44ba-4be7-9c18-c66f358b9d4b.png)

**Comment by giulianogrossi** [comment]
A new version of the framework, pyVHR 2.0, has been released. Please check if problems persist and report them for future bug fixes.

best
the pyVHR team
