### ISSUE TITLE
getErrors() missing 2 required positional arguments: 'timesES' and 'timesGT'

### ISSUE THREAD

**Issue by wgb-10** [phuselab/pyVHR#42]
On running the `start()` method of the `MultiMethodSuite` class I noticed that the `getErrors()` function does not take the `bvps` and `fps` variables:

https://github.com/phuselab/pyVHR/blob/2b1767d7daafc0f377e707cd39f4dbeff1706034/pyVHR/analysis/multi_method_suite.py#L279 
Like was done in `run_on_dataset()` in the `Pipeline` class here:
https://github.com/phuselab/pyVHR/blob/2b1767d7daafc0f377e707cd39f4dbeff1706034/pyVHR/analysis/pipeline.py#L411-L412
This is why the above error occurs.

**Comment by giulianogrossi** [comment]
A new version of the framework, pyVHR 2.0, has been released. Please check if problems persist and report them for future bug fixes.

best
the pyVHR team
