### ISSUE TITLE
Logical bug in VHRroutine 

### ISSUE THREAD

**Issue by jo-ym** [phuselab/pyVHR#47]
Hi, we want to cite this project so we research it.
But we found there may be a logical bug in the `./pyVHR/realtime/VHRroutine.py`.
The block of if-statement, line 192.
The counting method will count one more frame to the `sig_stride` (fps)?
So the number of the windows will be not correct.

**Comment by giulianogrossi** [comment]
A new version of the framework, pyVHR 2.0, has been released. Please check if problems persist and report them for future bug fixes.

best
the pyVHR team
