### ISSUE TITLE
Estimated HR output length is not match with its actual input

### ISSUE THREAD

**Issue by Lukious** [phuselab/pyVHR#52]
Hello, I use this project for measuring HR from video input.

I recorded a video with my camera (1920x1080 video, 30FPS) and get rPPG by using the pyVHR GUI kit(GUI.py) with the CHROM method.

But its output length is not matched its actual input

For example, If I input a 1261-sec video then I got only 1214-sec of HR for results. (It should be 1256-sec)
And If Input 316-sec video the results are only 299-sec. (It should be 311-sec)

I tried many different cases and figured out that this tendency follows a linear function.
So, it must be a problem with repeatable functions in this project. 
With this assumption,  me and my colleague tracking it now to solve this problem. 

We'll fix it ASAP but if anyone has some advice to fix it, please give us help. 👍

+We tried with 900-sec 25FPS video(counted frame, 22,500 exactly), but still not matched correctly.

**Comment by giulianogrossi** [comment]
A new version of the framework, pyVHR 2.0, has been released. Please check if problems persist and report them for future bug fixes.

best
the pyVHR team
