### ISSUE TITLE
heart rate is too high while using the GUI with the default parameters (CPU)

### ISSUE THREAD

**Issue by galharth** [phuselab/pyVHR#56]
My heart rate data is too high while using the GUI with the default parameters (CPU), around ~100, although my real heart rate is ~70. What are the common reasons that the heart rate is too high?

Thanks

**Comment by giulianogrossi** [comment]
the GUI version is still its early stage of development and deserves to be tested better. A nontrivial problem is having the correct reference signal from sensor. A second item to pay attention to is that the video is not compressed otherwise all functionality expires inexorably.

Berst
pyVHR team
