### ISSUE TITLE
Cannot find elementwisekernel in cupy

### ISSUE THREAD

**Issue by tikikun** [phuselab/pyVHR#57]
Hi everyone, after i try installing the same environment according to your env on the repo I try to run import Pipeline but i faced with the error:
```
Aattributeerror: module 'cupy' has no attribute 'elementwisekernel'
```

I try multiple ways to reinstall cupy through conda and pip but fail to overcome the issue. It seems that cupy 9.6 just doesn't have elementwisekernel.

What is going on here.

**Comment by giulianogrossi** [comment]
A new version of the framework, pyVHR 2.0, has been released. Please check if problems persist and report them for future bug fixes.

best
the pyVHR team
