### ISSUE TITLE
test on ubfc-phys gives bad results.

### ISSUE THREAD

**Issue by ycyoon** [phuselab/pyVHR#58]
I tested PURE, UBFC2, COFACE, and UBFC-Phys with mtts-can model.
Only a model trained with ubfc-phys gives bad results. (overfitted on the training dataset and fails on valid set)
I used s50~s56 as a valid set and trained with other videos.
Any idea? or does Anyone succeed in training with the UBFC-Phys dataset?

**Comment by giulianogrossi** [comment]
For mtts-can we used pretrained models as indicated in the paper. We have not done training experiment so it is difficult for us to make a judgment on this.

best
pyVHR team

**Comment by ccclu** [comment]
Why it showed really bad result when i use the pre-trained model to test UBFC videos? I just ran the demo_deep notebook. Do i need to do other things?
