### ISSUE TITLE
Pre-filtering Causes Error in run_on_video

### ISSUE THREAD

**Issue by jw1858** [phuselab/pyVHR#59]
Hey,

When using the run_on_video function, setting the pre_filt argument to True leads to the following error. It works fine when I set the pre_filt argument to False. 

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_5704\2147753529.py in <module>
      1 file = 'test.mp4'
----> 2 time, BPM, uncertainty = pipe.run_on_video(videoFileName = file, cuda=False, roi_method='convexhull', roi_approach='patches', method='cpu_CHROM', bpm_type='welch', pre_filt=True, post_filt=True, verb=True)
      3 plt.figure()
      4 plt.plot(time, BPM)
      5 plt.fill_between(time, BPM-uncertainty, BPM+uncertainty, alpha=0.2)

~\miniconda3\envs\pyvhr\lib\site-packages\pyVHR\analysis\pipeline.py in run_on_video(self, videoFileName, cuda, roi_method, roi_approach, method, bpm_type, pre_filt, post_filt, verb)
    128             module = import_module('pyVHR.BVP.filters')
    129             method_to_call = getattr(module, 'BPfilter')
--> 130             bvps = apply_filter(bvps, 
    131                                 method_to_call,
    132                                 fps=fps,

UnboundLocalError: local variable 'bvps' referenced before assignment
```
Looking at the code in the main repo, I assume there is some issue with implicit type casting when using the apply_filter function. 

Thanks,
Joe

ps. Great work on this project!

**Comment by giulianogrossi** [comment]
Hello,

the `run_on_video()` code is being refactored (like other code segments) because it has been used 
very little in the past and therefore little debugged, having favored `run_on_dataset()` for analysis 
extended to benchmarks.

Within a few weeks there will be a complete update of the framework.

Thanks for your interest and suggestions.

**Comment by giulianogrossi** [comment]
A new version of the framework pyVHR 2.0 has been released. Please check if problems persist and report them for future bug fixes.

best
the pyVHR team
