### ISSUE TITLE
run_on_video() pre-filtering part is never used

### ISSUE THREAD

**Issue by b-brebion** [phuselab/pyVHR#60]
Hello,
First of all, thanks for your great work.
I believe there is a problem in the `run_on_video()` function about the pre-filtering process (see the related part of the code below). If i'm not wrong `RGB_sig_to_BVP()` always takes `windowed_sig` as parameter, which means that the results of the two `apply_filter()` functions above are never used. And despite the fact that the lists are mutable, you use `copy()` when you apply the filters so `windowed_sig` is never modified.

---

`pyVHR/pipeline.py` (lines 120-158):
```python
# -- PRE FILTERING
filtered_windowed_sig = windowed_sig

# -- color threshold - applied only with patches
if roi_approach == 'patches':
    filtered_windowed_sig = apply_filter(windowed_sig, rgb_filter_th, params={'RGB_LOW_TH':  75, 'RGB_HIGH_TH': 230})

if pre_filt:
    module = import_module('pyVHR.BVP.filters')
    method_to_call = getattr(module, 'BPfilter')
    bvps = apply_filter(filtered_windowed_sig, method_to_call, fps=fps, params={'minHz':0.65, 'maxHz':4.0, 'fps':'adaptive', 'order':6})

# [...]

bvps = RGB_sig_to_BVP(windowed_sig, fps, device_type=method_device, method=method_to_call, params=pars)
```

**Comment by giulianogrossi** [comment]
Hello,

the `run_on_video()` code is being refactored (like other code segments) because it has been used 
very little in the past and therefore little debugged, having favored `run_on_dataset()` for analysis 
extended to benchmarks.

Within a few weeks there will be a complete update of the framework.

Thanks for your interest and suggestions.

**Comment by giulianogrossi** [comment]
A new version of the framework pyVHR 2.0 has been released. Please check if problems persist and report them for future bug fixes.

best
the pyVHR team
