### ISSUE TITLE
ImportError: 'median_absolute_deviation' from 'scipy.stats'

### ISSUE THREAD

**Issue by ckim0922** [phuselab/pyVHR#64]
Hi, 

I was just trying to run "basic usage and notebooks" on both Intel MacBook Pro & M2 MacBook Air.

On both devices, I am getting exactly the same error as below.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[3], line 1
----> 1 from pyVHR.analysis.pipeline import Pipeline
      2 import matplotlib.pyplot as plt
      4 pipe = Pipeline()

File ~/miniconda3/envs/pyvhr/lib/python3.10/site-packages/pyVHR/__init__.py:3
      1 import pyVHR.extraction
      2 import pyVHR.BVP
----> 3 import pyVHR.BPM
      4 import pyVHR.datasets
      5 import pyVHR.plot

File ~/miniconda3/envs/pyvhr/lib/python3.10/site-packages/pyVHR/BPM/__init__.py:1
----> 1 from .BPM import *
      2 from .utils import *

File ~/miniconda3/envs/pyvhr/lib/python3.10/site-packages/pyVHR/BPM/BPM.py:10
      8 from pyVHR.plot.visualize import VisualizeParams
      9 from pyVHR.BPM.utils import *
---> 10 from scipy.stats import median_absolute_deviation as mad
     12 """
     13 This module contains all the class and the methods for transforming 
     14 a BVP signal in a BPM signal.
     15 """
     18 class BVPsignal:

**ImportError: cannot import name 'median_absolute_deviation' from 'scipy.stats'** (/Users/chriskim/miniconda3/envs/pyvhr/lib/python3.10/site-packages/scipy/stats/__init__.py)

Would you be able to give me a hint as to how to fix this issue?
![Screenshot 2023-01-12 at 1 11 44 am](https://user-images.githubusercontent.com/80383901/211827787-86c716d8-6495-4057-b557-36b62bb8fe94.png)

**Comment by giulianogrossi** [comment]
A new version of the framework pyVHR 2.0 has been released. Please check if problems persist and report them for future bug fixes. Thanks!

Best
the pyVHR team
