### ISSUE TITLE
scipy.stats dependency

### ISSUE THREAD

**Issue by nbottenus** [phuselab/pyVHR#66]
Installed according to the README with miniconda (using the MinGW fortran compiler from the pull request #51 ), and found that when importing pyVHR got the following error:
![image](https://user-images.githubusercontent.com/4241114/212754529-16c88622-acc3-4768-b5e4-4700b4585530.png)

This seems to be resolved by changing `from scipy.stats import median_absolute_deviation as mad` to `from scipy.stats import median_abs_deviation as mad` in BPM.py. (scipy version 1.10.0 and statsmodels version 0.13.5)

**Comment by nbottenus** [comment]
I must have somehow pulled an older version and see this was fixed

**Comment by nbottenus** [comment]
Sorry for the confusion, this issue exists still in the pyVHR_CPU branch

**Comment by talhaanwarch** [comment]
Hi, may be you need to try the latest commit
pip install git+https://github.com/phuselab/pyVHR.git@pyVHR_CPU
