### ISSUE TITLE
Statistics not imported

### ISSUE THREAD

**Issue by nbottenus** [phuselab/pyVHR#67]
https://github.com/phuselab/pyVHR/blob/a2ea2aa12a9c7f5a3267a9e2626b7fbc37517bdf/pyVHR/realtime/VHRroutine.py#L282

This file needs `import statistics` to print frame times after processing

**Comment by giulianogrossi** [comment]
This version of realtime is still immature and not fully tested, we promise to develop a more usable version than the current one.

best
