### ISSUE TITLE
i cant install properly the pyVHR through pip any  suggestions i am working on windows and GPU with cuda version 10.1

### ISSUE THREAD

**Issue by saranzeb** [phuselab/pyVHR#7]
4d65715b129aee13d69f7d227e78e
  Building wheel for dlib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\saran\anaconda3\envs\pyt13\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\saran\\AppData\\Local\\Temp\\pip-install-x_xscd44\\dlib_37a5bd04b741435580d050a7fe5c76c0\\setup.py'"'"'; __file__='"'"'C:\\Users\\saran\\AppData\\Local\\Temp\\pip-install-x_xscd44\\dlib_37a5bd04b741435580d050a7fe5c76c0\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\saran\AppData\Local\Temp\pip-wheel-4elw3_ab'
       cwd: C:\Users\saran\AppData\Local\Temp\pip-install-x_xscd44\dlib_37a5bd04b741435580d050a7fe5c76c0\
  Complete output (53 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'dlib\__init__.py' not found (or not a regular file)
  running build_ext
  Traceback (most recent call last):
    File "C:\Users\saran\AppData\Local\Temp\pip-install-x_xscd44\dlib_37a5bd04b741435580d050a7fe5c76c0\setup.py", line 120, in get_cmake_version
      out = subprocess.check_output(['cmake', '--version'])
    File "C:\Users\saran\anaconda3\envs\pyt13\lib\subprocess.py", line 411, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "C:\Users\saran\anaconda3\envs\pyt13\lib\subprocess.py", line 489, in run
      with Popen(*popenargs, **kwargs) as process:
    File "C:\Users\saran\anaconda3\envs\pyt13\lib\subprocess.py", line 854, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Users\saran\anaconda3\envs\pyt13\lib\subprocess.py", line 1307, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] The system cannot find the file specified

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\saran\AppData\Local\Temp\pip-install-x_xscd44\dlib_37a5bd04b741435580d050a7fe5c76c0\setup.py", line 223, in <module>
      setup(
    File "C:\Users\saran\anaconda3\envs\pyt13\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\saran\anaconda3\envs\pyt13\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\saran\anaconda3\envs\pyt13\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\saran\anaconda3\envs\pyt13\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\saran\anaconda3\envs\pyt13\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\saran\anaconda3\envs\pyt13\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\saran\anaconda3\envs\pyt13\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\saran\anaconda3\envs\pyt13\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\saran\anaconda3\envs\pyt13\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\saran\anaconda3\envs\pyt13\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\saran\AppData\Local\Temp\pip-install-x_xscd44\dlib_37a5bd04b741435580d050a7fe5c76c0\setup.py", line 129, in run
      cmake_version = self.get_cmake_version()
    File "C:\Users\saran\AppData\Local\Temp\pip-install-x_xscd44\dlib_37a5bd04b741435580d050a7fe5c76c0\setup.py", line 122, in get_cmake_version
      raise RuntimeError("\n*******************************************************************\n" +
  RuntimeError:
  *******************************************************************
   CMake must be installed to build the following extensions: dlib
  *******************************************************************

  ----------------------------------------
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
  Building wheel for ipaddr (setup.py) ... done
  Created wheel for ipaddr: filename=ipaddr-2.2.0-py3-none-any.whl size=18280 sha256=2e8a90df4c48ac1c6a08bc3ef7166c1db0bf506d17381444c750011bfbc3bc02
  Stored in directory: c:\users\saran\appdata\local\pip\cache\wheels\38\59\0e\c20fbbd7969a095fa10b79bdde5d9852227f60bdbdd3a90b49
  Building wheel for msgpack (setup.py) ... done
  Created wheel for msgpack: filename=msgpack-0.6.2-cp38-cp38-win_amd64.whl size=73014 sha256=d5a26713cb0e9c4daba032eafecc1419a8fad4f1f84e90b48bc22359d003f7ba
  Stored in directory: c:\users\saran\appdata\local\pip\cache\wheels\5d\f2\04\0d19c10080b996bef17c908a6243e6e65d8da1a4094a3f604d
  Building wheel for bottleneck (PEP 517) ... done
  Created wheel for bottleneck: filename=Bottleneck-1.3.2-cp38-cp38-win_amd64.whl size=107737 sha256=e2e0f3e2c0758041116919653357bc64b47d47a4bca7293d8b1c434ef266f279
  Stored in directory: c:\users\saran\appdata\local\pip\cache\wheels\29\60\c9\98f744fb5c7d1ffb38d096318d9e873a08c0f5df07d6487626
  Building wheel for et-xmlfile (setup.py) ... done
  Created wheel for et-xmlfile: filename=et_xmlfile-1.0.1-py3-none-any.whl size=8915 sha256=41c445068586f7428cb5efafbff1f3b8754db2476d3af4eced353be57b9dd7fd
  Stored in directory: c:\users\saran\appdata\local\pip\cache\wheels\6e\df\38\abda47b884e3e25f9f9b6430e5ce44c47670758a50c0c51759
  Building wheel for progress (setup.py) ... done
  Created wheel for progress: filename=progress-1.5-py3-none-any.whl size=8073 sha256=34e5f7b2d179509c5258f4b2ded26bc4cf46c06e99c23733cfa79b6770db2999
  Stored in directory: c:\users\saran\appdata\local\pip\cache\wheels\f1\5b\38\115b213dfbf5562108ea22df17c063f6378350205a819795aa
  Building wheel for pybdf (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\saran\anaconda3\envs\pyt13\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\saran\\AppData\\Local\\Temp\\pip-install-x_xscd44\\pybdf_1225b8add233498aadfb1268ce560e2b\\setup.py'"'"'; __file__='"'"'C:\\Users\\saran\\AppData\\Local\\Temp\\pip-install-x_xscd44\\pybdf_1225b8add233498aadfb1268ce560e2b\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\saran\AppData\Local\Temp\pip-wheel-30hapa_l'
       cwd: C:\Users\saran\AppData\Local\Temp\pip-install-x_xscd44\pybdf_1225b8add233498aadfb1268ce560e2b\
  Complete output (50 lines):
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building py_modules sources
  building extension "libforbdf" sources
  f2py options: []
    adding 'build\src.win-amd64-3.8\build\src.win-amd64-3.8\fortranobject.c' to sources.
    adding 'build\src.win-amd64-3.8\build\src.win-amd64-3.8' to include_dirs.
  build_src: building npy-pkg config files
  running build_py
  creating build\lib.win-amd64-3.8
  copying pybdf.py -> build\lib.win-amd64-3.8
  running build_ext
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  customize MSVCCompiler using build_ext
  get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
  customize GnuFCompiler
  Could not locate executable g77
  Could not locate executable f77
  customize IntelVisualFCompiler
  Could not locate executable ifort
  Could not locate executable ifl
  customize AbsoftFCompiler
  Could not locate executable f90
  customize CompaqVisualFCompiler
  Could not locate executable DF
  customize IntelItaniumVisualFCompiler
  Could not locate executable efl
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize G95FCompiler
  Could not locate executable g95
  customize IntelEM64VisualFCompiler
  customize IntelEM64TFCompiler
  Could not locate executable efort
  Could not locate executable efc
  customize PGroupFlangCompiler
  Could not locate executable flang
  don't know how to compile Fortran code on platform 'nt'
  warning: build_ext: f77_compiler=None is not available.

  building 'libforbdf' extension
  error: extension 'libforbdf' has Fortran sources but no Fortran compiler found
  ----------------------------------------
  ERROR: Failed building wheel for pybdf
  Running setup.py clean for pybdf
  Building wheel for python-louvain (setup.py) ... done
  Created wheel for python-louvain: filename=python_louvain-0.15-py3-none-any.whl size=9401 sha256=9281fb48affe483e2cb86ce92e610b6922398a90768984819b4ed44582359914
  Stored in directory: c:\users\saran\appdata\local\pip\cache\wheels\c8\68\21\d04741956802581119d875a0d9fce6895e8f9ffae71223f3e3
  Building wheel for retrying (setup.py) ... done
  Created wheel for retrying: filename=retrying-1.3.3-py3-none-any.whl size=11430 sha256=22628f0401c5a0864859fec4407cc25f8062fd3ab4b9ae0e809501468abfd6ca
  Stored in directory: c:\users\saran\appdata\local\pip\cache\wheels\c4\a7\48\0a434133f6d56e878ca511c0e6c38326907c0792f67b476e56
  Building wheel for serverfiles (setup.py) ... done
  Created wheel for serverfiles: filename=serverfiles-0.3.1-py3-none-any.whl size=6932 sha256=a96c94824b7089fe45cb3c924fc02ed15622fd37ced925076d7b4cb352988bc8
  Stored in directory: c:\users\saran\appdata\local\pip\cache\wheels\84\4b\a4\233da5e4477309b7a6e38f3e48511005fcfd1e4a2a8c4be34f
  Building wheel for termcolor (setup.py) ... done
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4832 sha256=d52e9091cf68ef7fc4ba95cda8208a74d7b7dd3b4d4d37a23284ee2c48426d19
  Stored in directory: c:\users\saran\appdata\local\pip\cache\wheels\a0\16\9c\5473df82468f958445479c59e784896fa24f4a5fc024b0f501
  Building wheel for pandocfilters (setup.py) ... done
  Created wheel for pandocfilters: filename=pandocfilters-1.4.3-py3-none-any.whl size=7991 sha256=2bc94e4e17831b634547aa6f10a5befad24685407e9c473684cb681ddbcef798
  Stored in directory: c:\users\saran\appdata\local\pip\cache\wheels\fc\39\52\8d6f3cec1cca4ceb44d658427c35711b19d89dbc4914af657f
Successfully built distlib ipaddr msgpack bottleneck et-xmlfile progress python-louvain retrying serverfiles termcolor pandocfilters
Failed to build dlib pybdf
Installing collected packages: ipython-genutils, traitlets, six, pywin32, wcwidth, urllib3, pyzmq, pyparsing, parso, jupyter-core, idna, certifi, webencodings, requests, pygments, prompt-toolkit, pickleshare, packaging, nest-asyncio, nbformat, msgpack, MarkupSafe, jupyter-client, jedi, decorator, colorama, backcall, async-generator, testpath, pywinpty, pandocfilters, nbclient, mistune, lockfile, jupyterlab-pygments, jinja2, ipython, entrypoints, defusedxml, CacheControl, bleach, terminado, sniffio, Send2Trash, scipy, rfc3986, qasync, pytz, PyQt5-sip, prometheus-client, nbconvert, ipykernel, h11, docutils, dictdiffer, commonmark, argon2-cffi, AnyQt, scikit-learn, pyyaml, pywin32-ctypes, pyqtgraph, PyQt5, patsy, pandas, orange-canvas-core, notebook, networkx, matplotlib, jdcal, httpcore, et-xmlfile, xlsxwriter, xlrd, widgetsnbextension, tifffile, termcolor, tensorflow-estimator, tensorboard, statsmodels, shortuuid, serverfiles, seaborn, retrying, PyWavelets, python-louvain, PyQtWebEngine, orange-widget-base, opt-einsum, openTSNE, openpyxl, opencv-python, numexpr, keyrings.alt, keyring, keras-preprocessing, keras, imageio, httpx, google-pasta, gast, bottleneck, bidict, baycomp, astunparse, tensorflow, tables, scikit-video, scikit-posthocs, scikit-image, pytoml, pybdf, progress, plotly, pep517, orange3, mtcnn, ipywidgets, ipaddr, html5lib, dlib, distro, distlib, contextlib2, biosppy, appdirs, pyvhr
  Attempting uninstall: six
    Found existing installation: six 1.15.0
    Uninstalling six-1.15.0:
      Successfully uninstalled six-1.15.0
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.2
    Uninstalling urllib3-1.26.2:
      Successfully uninstalled urllib3-1.26.2
  Attempting uninstall: pyparsing
    Found existing installation: pyparsing 2.4.7
    Uninstalling pyparsing-2.4.7:
      Successfully uninstalled pyparsing-2.4.7
  Attempting uninstall: idna
    Found existing installation: idna 2.10
    Uninstalling idna-2.10:
      Successfully uninstalled idna-2.10
  Attempting uninstall: certifi
    Found existing installation: certifi 2020.12.5
    Uninstalling certifi-2020.12.5:
      Successfully uninstalled certifi-2020.12.5
  Attempting uninstall: requests
    Found existing installation: requests 2.25.0
    Uninstalling requests-2.25.0:
      Successfully uninstalled requests-2.25.0
  Attempting uninstall: colorama
    Found existing installation: colorama 0.4.4
    Uninstalling colorama-0.4.4:
      Successfully uninstalled colorama-0.4.4
  Attempting uninstall: scipy
    Found existing installation: scipy 1.6.1
    Uninstalling scipy-1.6.1:
      Successfully uninstalled scipy-1.6.1
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.23.2
    Uninstalling scikit-learn-0.23.2:
      Successfully uninstalled scikit-learn-0.23.2
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.3.2
    Uninstalling matplotlib-3.3.2:
      Successfully uninstalled matplotlib-3.3.2
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.4.0
    Uninstalling tensorboard-2.4.0:
      Successfully uninstalled tensorboard-2.4.0
    Running setup.py install for pybdf ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\saran\anaconda3\envs\pyt13\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\saran\\AppData\\Local\\Temp\\pip-install-x_xscd44\\pybdf_1225b8add233498aadfb1268ce560e2b\\setup.py'"'"'; __file__='"'"'C:\\Users\\saran\\AppData\\Local\\Temp\\pip-install-x_xscd44\\pybdf_1225b8add233498aadfb1268ce560e2b\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\saran\AppData\Local\Temp\pip-record-o_2raxtq\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\saran\anaconda3\envs\pyt13\Include\pybdf'
         cwd: C:\Users\saran\AppData\Local\Temp\pip-install-x_xscd44\pybdf_1225b8add233498aadfb1268ce560e2b\
    Complete output (50 lines):
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building py_modules sources
    building extension "libforbdf" sources
    f2py options: []
      adding 'build\src.win-amd64-3.8\build\src.win-amd64-3.8\fortranobject.c' to sources.
      adding 'build\src.win-amd64-3.8\build\src.win-amd64-3.8' to include_dirs.
    build_src: building npy-pkg config files
    running build_py
    creating build\lib.win-amd64-3.8
    copying pybdf.py -> build\lib.win-amd64-3.8
    running build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    customize MSVCCompiler using build_ext
    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Could not locate executable DF
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize G95FCompiler
    Could not locate executable g95
    customize IntelEM64VisualFCompiler
    customize IntelEM64TFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize PGroupFlangCompiler
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
    warning: build_ext: f77_compiler=None is not available.

    building 'libforbdf' extension
    error: extension 'libforbdf' has Fortran sources but no Fortran compiler found
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\saran\anaconda3\envs\pyt13\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\saran\\AppData\\Local\\Temp\\pip-install-x_xscd44\\pybdf_1225b8add233498aadfb1268ce560e2b\\setup.py'"'"'; __file__='"'"'C:\\Users\\saran\\AppData\\Local\\Temp\\pip-install-x_xscd44\\pybdf_1225b8add233498aadfb1268ce560e2b\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\saran\AppData\Local\Temp\pip-record-o_2raxtq\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\saran\anaconda3\envs\pyt13\Include\pybdf' Check the logs for full command output.

**Comment by vcuculo** [comment]
@saranzeb you have missing dependencies: `cmake` requested by `dlib` and `gfortran` requested by `pybdf`

**Comment by saranzeb** [comment]
> @saranzeb you have missing dependencies: `cmake` requested by `dlib` and `gfortran` requested by `pybdf`

ok thank you so first i need to install these two packages ?
and can i install it on google colab as it have already installed most of the dependencies  ?

**Comment by vcuculo** [comment]
yes, sure
