### ISSUE TITLE
Performance on darker skin tones

### ISSUE THREAD

**Issue by ubblechristophe** [phuselab/pyVHR#8]
Hi there!
thanks for this great work it is really impressive!

By any chance have you ever tested these solutions on darker skin tones? It seems it is a major limitation of rPPG, I was wondering if you have some clues on how to tackle it

Thanks!

Best

**Comment by vcuculo** [comment]
Hi @ubblechristophe thank you for your feedback!
The impact of skin type on VHR methods is still an open issue, especially on darker skin tones. You can find an interesting meta-analysis here [Nowara, E. M., McDuff, D., & Veeraraghavan, A. (2020). A meta-analysis of the impact of skin tone and gender on non-contact photoplethysmography measurements. In Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition Workshops (pp. 284-285).](https://openaccess.thecvf.com/content_CVPRW_2020/papers/w19/Nowara_A_Meta-Analysis_of_the_Impact_of_Skin_Tone_and_Gender_CVPRW_2020_paper.pdf)
